dist: trusty
sudo: false
language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
deploy:
  provider: heroku
  api_key:
    secure: Srk6Jdcy1YFmOubZiLWKMlu325bQAWesJYlNXmdIp6H9nx+s/89jxjbm1lcYmoL5lFW1g+WyD04mwZJB/anTBrnWPRwy9OIBmewwoMedVyd4QT4RJ9aBicpsrUKRmOMwcO/g36DCD4M06bgoW7XkQPp4BMfDTDhD+dBU+aJPh/7F4aNzjux8OLnFesqyYau+ITs3SAaKxxhyScSkOmWLh1VW3ZKgBb2m4/jV9I3kNkRXW/jl1FrUX5ZHMvNSurIRqFpkenYZ0KmclLCSUX1mbiyEbhzYoABtBcqkciCJcH7twPRqm+5epyKr+IqyswgbD2Vd9msVzoz8zK9ctsE3Q8gSY8ssESltKKcmagelIODJN6ZLrDcCdo8Yf2vbgZJ3VcXErc+Ioak/iJa2cXAMaqNTGJpkq/B500MtMSNtYBFgSY2NzzOAgRNQOnXEVDdB5kTQ2EHaZcDTuhCx7F8PtYtvX/W4YVw5kyXNFQV9qbQwokM/SP2lqkoGlN5zCU1pzbIp5JmVFwj5xDiXqbGAAqaYIa8H0s1C91VsVWDAB0abjiF5pem5UUcpuwqksxEpthaJVyxVkH5xu6wxLUCQ62axnks39uMgMDax8OuwGFIfV2Ka2wIhJ0244MZfSk29t2BJOXJI0uy0+bweIMWXww5jCFuRHTEDvPuBQlzg9oA=
