firefox: latest

language: node_js
node_js:
  - "10.15.1"

deploy:
  provider: heroku
  api_key:
    secure: N9mjXXl1mItle0sFM8MtqA8j86cDb7zg24/ByHjAne+nnximp1U6opHRyZnzPTlLYtxiyleiNkg9dh22+H7wrBNSJX4raQUuZT7QNPW6iSmwfr1roKkX0MSYdiT4I4ZDchUpA4MJBEGtkzlriy1+n1eyMoNjCydiBlvlxStjBIAweQJmeTzn5/RPoHpj5zP8KocEcxGiqPDHfUQK4b/fMo5NfuvJQCYStNzwPYrKviXhs2jRG1vGEaIImFP1xxz4rpIc9Vd3x4MrgHzVc2KD6ddNfbvGhxexlvDbR/DT/jrQtPzDq0LsTlztmg0dRwxg8bbPzZx+TIzDZBUqDwl0kjNG/ZnobGLjb9pwS0qb4WejVgm2wn+LLRnvsdes48+enT/NbuyvFYp60wUqogTkIqfWz62fAbJlTRrknsR6sWDjez3od7VPa7+/S2JxRyL99BtGzZvW6GRLxqyg3OhsNiYYhw+lVCBjsDeQOJ1DEv02N/7QwbQ4fk5sE4tDNbG0EhgnYB2D7qCeev9yMgi9c3U32tW1qkHVwQflSdCTSOO/rFFrruFXckNNZMC+ng6q8GFsFUiK5bRpHHVccsLN3xH/0CAoGTpytFNwtNFYwfcUuzrQfpatLB7D6tzrQwf+daQFP6URsX1ihpeOQPQRxWjOIzGdCRLkiCzHQngppQU=
